/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bookcompany;
import java.sql.*;
/**
 *
 * @author user
 */
public class SalesReport extends javax.swing.JFrame {

    /**
     * Creates new form SalesReport
     */
    public SalesReport(Connection c) {
        initComponents();
        jTextArea1.setEditable(false);
        con = c;
        
        
        try {
           Statement S = con.createStatement();
           Statement S2 = con.createStatement();
           Statement S3 = con.createStatement();
            
           String Query = "SELECT OrderLine.OrderNumber, sum(OrderLine.Quantity * Book.Price) AS Sub_Total FROM OrderLine, Book WHERE Book.ISBN = OrderLine.ISBN GROUP BY OrderLine.OrderNumber";
           ResultSet R = S.executeQuery(Query);
           String Query2 = "SELECT CustomerID FROM Order1 GROUP BY CustomerID";
           ResultSet R2 = S2.executeQuery(Query2);
           
           
           while (R.next() && R2.next())
           {
               String B = R.getString("OrderNumber");
               String Query3 = "SELECT Book.ISBN, OrderLine.Quantity , Book.Price FROM Book, OrderLine WHERE Book.ISBN = OrderLine.ISBN AND OrderLine.OrderNumber =" + B;
               ResultSet R3 = S3.executeQuery(Query3);
               
               jTextArea1.append("\t\tOrder Number : ");
               jTextArea1.append(B);
               jTextArea1.append("\t\tCustomer ID : ");
               jTextArea1.append(R2.getString("CustomerID"));
               jTextArea1.append("\n\t\tISBN\t\tQuantity\t\t Unit Price\n");
               
               
               while (R3.next())
               {
                   jTextArea1.append("\t\t" + R3.getString("ISBN"));
                   jTextArea1.append("\t\t");
                   jTextArea1.append(R3.getString("Quantity"));
                   jTextArea1.append("\t\t");
                   jTextArea1.append(R3.getString("Price"));
                   jTextArea1.append("\n");
               }
               
               jTextArea1.append("\t\t\t\t\t\t\tSubTotal For The Order: ");
               jTextArea1.append(R.getString("Sub_Total"));
               jTextArea1.append("\n\n\n");
            }
            
            Query = "SELECT Sum(OrderLine.Quantity) AS Total_Books_Sold FROM OrderLine";
            R = S.executeQuery(Query);
            
            jTextArea1.append("\t\tQuantity Of Books Sold Till Date : ");
            while (R.next())
            {
                jTextArea1.append(R.getString("Total_Books_Sold"));
            }
            
            Query = "SELECT sum(Order1.TotalCost) AS Total FROM Order1";
            R = S.executeQuery(Query);
            
            jTextArea1.append("\n\t\tTotal Sales Till Date : ");
            while (R.next())
            {
                jTextArea1.append(R.getString("Total"));
            }
            
           jTextField1.setText("The report is generated");
        } catch (Exception e){
            jTextField1.setText("Error: " + e);
        }
          
    }
    
    
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Report For The Sales");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1052, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesReport(con).setVisible(true);
            }
        });
        
    }
    
    public static Connection con;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
